all: init destroy set check

init: init.cpp
	g++ -o init init.cpp

destroy: destroy.cpp
	g++ -o destroy destroy.cpp

set: set.cpp
	g++ -o set set.cpp

check: check.cpp
	g++ -o check check.cpp


clean:
	rm init destroy set check
