all: spinlock mutex semaphore

spinlock: spinlock.cpp
	g++ spinlock.cpp -o spinlock

mutex: mutex.cpp
	g++ mutex.cpp -o mutex

semaphore: semaphore.cpp
	g++ semaphore.cpp -o semaphore

clean:
	rm spinlock mutex semaphore

