all: signal-receiver signal-sender

signal-receiver: signal-receiver.cpp
	g++ signal-receiver.cpp -o signal-receiver

signal-sender: signal-sender.cpp
	g++ signal-sender.cpp -o signal-sender

clean:
	rm signal-sender signal-receiver
